version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - ${API_PORT}:${API_PORT}

  db:
    image: postgres:11.5
    restart: always
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER= ${DB_USERNAME}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - POSTGRES_DB= ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
